apiVersion: v1
kind: Secret
metadata:
  name: cosmic-view-secret
  namespace: cosmic
type: Opaque

data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9rc2hpdmFuZzY3OV9kYl91c2VyOjRrUW1ncjBWT0Q1TDJnR2ZAY2x1c3RlcjAucWp1MmlhbC5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==

  JWT_SECRET: c2hpdnV1dUAxNDEyMjI=
  NASA_API_KEY: WXAwUjhEWWd4M2VwbWNoRm10a3BMUndXZHdVWXJDWjVlZ1A4VEtCUA==
