apiVersion: v1
kind: Service
metadata:
  name: cosmic-view-service
  namespace: cosmic

spec:
  type: LoadBalancer

  selector:
    app: cosmic-view

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
